# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runabout < Formula
  desc "Personal developer tools  -  mdq, bmux, workctl, linkari, runway, and more"
  homepage "https://github.com/thebrianlopez/runabout"
  version "0.2.57"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.57/runabout_0.2.57_darwin_amd64.tar.gz"
      sha256 "b9ac0ab6103654fe9f8612ac567b90dd8b93db2b97f6c054969f2dd1aee7cb17"

      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.57/runabout_0.2.57_darwin_arm64.tar.gz"
      sha256 "e17b561257e7578772927f3646fec8beeb66742702d6470c5d2bf537c18c43bd"

      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.57/runabout_0.2.57_linux_amd64.tar.gz"
      sha256 "99de09cd6f73a362df3b37597519883948f10ec4343d54a0bf250084ce480523"
      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.57/runabout_0.2.57_linux_arm64.tar.gz"
      sha256 "3aacd486dc71acf5a7d94a00dfa37e934fec900e83d83ae044a02b0bcd12ec32"
      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
  end

  test do
    system "#{bin}/mdq", "--version"
    system "#{bin}/bmux", "--version"
    system "#{bin}/workctl", "--version"
    system "#{bin}/castex", "--version"
  end
end
