# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runabout < Formula
  desc "Personal developer tools  -  mdq, bmux, workctl, linkari, runway, and more"
  homepage "https://github.com/thebrianlopez/runabout"
  version "0.2.54"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.54/runabout_0.2.54_darwin_amd64.tar.gz"
      sha256 "2a52f49280f4da4aad1a3e43883d3723f2215eea8d89a6f467bad63f3d25f556"

      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.54/runabout_0.2.54_darwin_arm64.tar.gz"
      sha256 "aedb3c9f1950b2d0b53952229d77eba0b5f4be3be0c8079266fda8ce77cbfd67"

      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.54/runabout_0.2.54_linux_amd64.tar.gz"
      sha256 "154837ab8f9a2c0ebe29d3602bccd0af08b322cb3c4bb9bddb3bcb71ad067086"
      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.54/runabout_0.2.54_linux_arm64.tar.gz"
      sha256 "872740678dad1ac06b09547cbe4cf573f152164b839c07519f9efa662e297dc0"
      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
  end

  test do
    system "#{bin}/mdq", "--version"
    system "#{bin}/bmux", "--version"
    system "#{bin}/workctl", "--version"
    system "#{bin}/castex", "--version"
  end
end
