# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runabout < Formula
  desc "Personal developer tools  -  mdq, bmux, workctl, linkari, runway, and more"
  homepage "https://github.com/thebrianlopez/runabout"
  version "0.2.53"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.53/runabout_0.2.53_darwin_amd64.tar.gz"
      sha256 "d02c109b57b8c265c252dc3e74e2a68365d9a7f38461646a792b0ce320cab998"

      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.53/runabout_0.2.53_darwin_arm64.tar.gz"
      sha256 "bdc1e3acd01a602143fe52c28c43d4742648e5976134dd9e0af60cd25b996c4e"

      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.53/runabout_0.2.53_linux_amd64.tar.gz"
      sha256 "d173167d9891c3c9a89b68e4a32e98909591e09f8bb7cc18e2353d61f05ef7df"
      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.53/runabout_0.2.53_linux_arm64.tar.gz"
      sha256 "1f746212f7a88f7eb795f50733d90e3164902e97a52713db6dfaa61c36474964"
      define_method(:install) do
        bin.install "mdq"
        bin.install "perfgate"
        bin.install "shellprof"
        bin.install "hookval"
        bin.install "effiscore"
        bin.install "castex"
        bin.install "chain-eval"
        bin.install "bmux"
        bin.install "protonexport"
        bin.install "linkari"
        bin.install "linkari-labeler"
        bin.install "plaid-service"
        bin.install "wasend"
        bin.install "workctl"
        bin.install "ghwatch"
        bin.install "jira-poller"
        bin.install "runway"
      end
    end
  end

  test do
    system "#{bin}/mdq", "--version"
    system "#{bin}/bmux", "--version"
    system "#{bin}/workctl", "--version"
    system "#{bin}/castex", "--version"
  end
end
