# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TsGo < Formula
  desc "Tree-sitter-based structural Go source analysis CLI"
  homepage "https://github.com/thebrianlopez/runabout"
  version "0.2.6"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.6/ts-go_0.2.6_darwin_amd64.tar.gz"
    sha256 "cb81ef38eb5133c62b224f375d82ad9a025de6117dcb7d4ae4a22545e5643064"

    define_method(:install) do
      bin.install "ts-go"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/thebrianlopez/runabout/releases/download/v0.2.6/ts-go_0.2.6_darwin_arm64.tar.gz"
    sha256 "b417a1d2e5c0ac31153fb74b253dde7c65e8fd1433dcc7c1b030da395654b7ba"

    define_method(:install) do
      bin.install "ts-go"
    end
  end

  test do
    system "#{bin}/ts-go", "--version"
  end
end
